# Generated by Django 4.0.6 on 2022-08-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
