# Generated by Django 4.0.6 on 2022-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='pic_link',
            field=models.CharField(default='https://www.citypng.com/public/uploads/preview/warranty-ribbon-blue-icon-logo-sign-label-badge-png-11635941164yp8i70hmcb.png', max_length=400),
        ),
    ]
