# Generated by Django 4.0.6 on 2022-08-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0003_offer_pic_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('Food', 'تغذیه'), ('Intertainment', 'تفریحی'), ('Service', 'خدماتی'), ('Applicable', 'کاربردی'), ('Other', 'متفرقه')], default='Other', max_length=20),
        ),
    ]
