# Generated by Django 4.0.6 on 2022-08-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.CharField(choices=[('تغذیه', 'تغذیه'), ('تفریحی', 'تفریحی'), ('خدماتی', 'خدماتی'), ('کاربردی', 'کاربردی'), ('متفرقه', 'متفرقه')], default='متفرقه', max_length=20),
        ),
    ]
