# Generated by Django 4.0.6 on 2022-08-09 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_provider', models.BooleanField()),
                ('phone_no', models.CharField(max_length=20)),
                ('pic_link', models.CharField(default='https://www.citypng.com/public/uploads/preview/warranty-ribbon-blue-icon-logo-sign-label-badge-png-11635941164yp8i70hmcb.png', max_length=400)),
                ('orgname', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('license_link', models.CharField(max_length=400, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('location', location_field.models.plain.PlainLocationField(default=None, max_length=63)),
                ('fav_offers', models.ManyToManyField(to='offer.offer')),
                ('fav_providers', models.ManyToManyField(blank=True, to='user.myuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
