# Generated by Django 4.0.6 on 2022-08-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_myuser_licence_link_alter_myuser_pic_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='licence_link',
            new_name='license_link',
        ),
    ]
