# Generated by Django 4.0.6 on 2022-08-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_licence_link_myuser_license_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='fav_providers',
            field=models.ManyToManyField(blank=True, to='user.myuser'),
        ),
    ]
