# Generated by Django 4.0.6 on 2022-08-07 17:15

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_myuser_fav_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=None, max_length=63),
        ),
    ]
